### PR TITLE
Add zh_CN.lang

### PR DESCRIPTION
**Pull request by chawyehsu**

### CODE REVIEW

**Comment by 3TUSK** [comment]
@h404bi If you see this message by any chance: Have you ever played Minecraft with [Ex Nihilo](https://minecraft.curseforge.com/projects/ex-nihilo)?

**Comment by chawyehsu** [comment]
@3TUSK yeah, for a period of time.

**Comment by 3TUSK** [comment]
Notice that there are some difference between your translation and the corresponding entries from Ex Nihilo. I wonder why you did these changes...

**Comment by chawyehsu** [comment]
@3TUSK 
Thank you for throwing the question out. I assume that you want to express - why not keep using the translation in Ex Nihilo. 
1. this new mod is **not** Ex Nihilo, and it _does_ have some difference from latter, in `en_US.lang`. e.g.
   
   ```
   # Ex Nihilo
   exnihilo.nether_copper_gravel.name=Copper Ore Gravel
   exnihilo.crook.name=Crook
   exnihilo.crook_bone.name=Bone Crook
   exnihilo.doll_creepy.name=Creepy Doll
   exnihilo.doll.name=Precious Doll
   exnihilo.doll_creepy.name=Creepy Doll
   
   # Ex Nihilo Omnia
   tile.ore_gravel_nether.copper.name= Nether Copper Ore Gravel
   item.crook_wood.name=Wooden Crook
   item.crook_bone.name=Bone Crook
   item.porcelain_doll.name= Porcelain Doll
   item.doll_ender.name= Spooky Doll
   ```
2. previous translation of some general terms _seems_ didn't follow [Minecraft_Wiki:译名标准化](http://minecraft-zh.gamepedia.com/Minecraft_Wiki:%E8%AF%91%E5%90%8D%E6%A0%87%E5%87%86%E5%8C%96).
   
   ```
   # Ex Nihilo
   ore 矿
   gravel 砂砾
   witch (witchwater) 巫（巫水）
   
   # Minecraft_Wiki:译名标准化
   ore 矿石
   gravel 沙砾
   witch 女巫
   ```
3. personal reason, different personal sense, typo or else.

If you have any suggestion, feel free to have a disscusion. Besides, I made minor changes on current translation (not submit yet).

``` diff
diff --git a/src/main/resources/assets/exnihiloomnia/lang/zh_CN.lang b/src/main/resources/assets/exnihiloomnia/lang/zh_CN.lang
index 43d57e0..0c2073e 100644
--- a/src/main/resources/assets/exnihiloomnia/lang/zh_CN.lang
+++ b/src/main/resources/assets/exnihiloomnia/lang/zh_CN.lang
@@ -1,5 +1,5 @@
-itemGroup.tabOre=Ex Nihilo Omnia 矿石
-itemGroup.tabElse=Ex Nihilo Omnia
+itemGroup.tabOre=无中生有-世间万物|矿石
+itemGroup.tabElse=无中生有-世间万物

 fluid.azoth=水银
 fluid.witchwater=女巫之水
@@ -150,10 +150,10 @@ tile.ore_dust.osmium.name= 锇矿石尘土

 item.seed_oak.name=橡子
 item.seed_dark_oak.name=大橡子
-item.seed_spruce.name=云杉种子
-item.seed_acacia.name=金合欢种子
-item.seed_birch.name=桦木种子
-item.seed_jungle.name=丛林种子
+item.seed_spruce.name=云杉树种子
+item.seed_acacia.name=金合欢树种子
+item.seed_birch.name=白桦树种子
+item.seed_jungle.name=丛林树种子

 item.doll_blaze.name= 愤怒人偶
 item.doll_ender.name= 惊悚人偶
@@ -175,7 +175,7 @@ item.crook_bone.name=骨钩
 item.hammer_wood.name=木锤
 item.hammer_stone.name=石锤
 item.hammer_iron.name=铁锤
-item.hammer_gold.name=黄金锤
+item.hammer_gold.name=金锤
 item.hammer_diamond.name=钻石锤
 item.astrolabe_jade.name=玉制星盘
 item.mesh_silk_white.name=丝网
@@ -189,14 +189,14 @@ item.seeds_grass.name=草种子
 item.seeds_carrot.name=胡萝卜种子
 item.seeds_cactus.name=仙人掌种子
 item.seeds_sugarcane.name=甘蔗种子
-item.stone.name=小石子
+item.stone.name=石子
 tile.barrel_glass.name=玻璃桶
 tile.barrel_glass_colored_white.name=白色玻璃桶
 tile.barrel_glass_colored_orange.name=橙色玻璃桶
 tile.barrel_glass_colored_magenta.name=品红色玻璃桶
 tile.barrel_glass_colored_light_blue.name=浅蓝色玻璃桶
 tile.barrel_glass_colored_yellow.name=黄色玻璃桶
-tile.barrel_glass_colored_lime.name=绿黄色玻璃桶
+tile.barrel_glass_colored_lime.name=黄绿色玻璃桶
 tile.barrel_glass_colored_pink.name=粉色玻璃桶
 tile.barrel_glass_colored_gray.name=灰色玻璃桶
 tile.barrel_glass_colored_silver.name=浅灰色玻璃桶
@@ -210,7 +210,7 @@ tile.barrel_glass_colored_black.name=黑色玻璃桶
 tile.barrel_stone.name=石桶
 tile.barrel_wood_oak.name=橡木桶
 tile.barrel_wood_spruce.name=云衫木桶
-tile.barrel_wood_birch.name=白桦木桶
+tile.barrel_wood_birch.name=桦木桶
 tile.barrel_wood_jungle.name=丛林木桶
 tile.barrel_wood_acacia.name=金合欢木桶
 tile.barrel_wood_dark_oak.name=深色橡木桶
@@ -222,7 +222,7 @@ tile.gravel_ender.name=末影沙砾
 tile.furnace_dirt.name=熔炉
 tile.sieve_wood_oak.name=橡木筛子
 tile.sieve_wood_spruce.name=云衫木筛子
-tile.sieve_wood_birch.name=白桦木筛子
+tile.sieve_wood_birch.name=桦木筛子
 tile.sieve_wood_jungle.name=从林木筛子
 tile.sieve_wood_acacia.name=金合欢木筛子
 tile.sieve_wood_dark_oak.name=深色橡木筛子
```

P.S.: I don't know what `Omnia` actually means in this mod. The word `世间万物` refer from [here](http://www.mcbbs.net/forum.php?mod=viewthread&tid=631637), the post author said he asked this mod's author (@Jozufozu ) what is the word's meaning. And as said, it means "everything".

**Comment by 3TUSK** [comment]
- Isn't Ex Nihilo Omnia a spiritual successor of Ex Nihilo? 
- 橡子 -> 橡木种子；大橡子 -> 深色橡木种子？
- Do you know that there is a [Mod Translation Style Guideline](https://github.com/Meow-J/Mod-Translation-Styleguide)? 
- ~~"Omnia", from my understanding, is a pseudo-Latin word (probably, _omnius, -a, -um_) means "universal". AFAIK, in Latin "omni" is a valid prefix but _not_ an individual word.~~ Didn't realize that ["omnia"](https://en.wiktionary.org/wiki/omnia#Latin) is a valid Latin word. So yeah "Ex Nihilo Omnia" roughly means "Everything out of nothing".
- For now - I suggest [not to translate the mod name](https://github.com/Meow-J/Mod-Translation-Styleguide#06mod名翻译). 
- Doesn't things like "锇矿石尘土" sounds weird? How about "锇矿砂" or "锇矿沙"?

**Comment by chawyehsu** [comment]
@3TUSK 
- Yes, thus I have read Ex Nihilo's language files for reference.
- Yes, using "橡木种子" and "深色橡木种子" looks more uniform. But you know, the original are:
  
  ```
  item.seed_oak.name=Acorn
  item.seed_dark_oak.name=Large Acorn
  ```
  
  Instead paraphrase, doesn't we use the literal translation first?[[1]](https://github.com/Meow-J/Mod-Translation-Styleguide#01普适原则) Furthermore, I think they should be "橡树种子" and "深色橡树种子" even though we use paraphrase. 
- I know that[[2]](https://github.com/Meow-J/Mod-Translation-Styleguide/stargazers), you guys do a great job!
- Thank you for the reference!
- I agree with you to not to translate that, stay `Ex Nihilo Omnia`.
- Well, I guess it maybe because of the mixed use of "石" and "尘土" (though I don't think it sounds weird...). Again the original text is `Osmium Ore Dust`.
  I notice that in [[3]](https://github.com/Meow-J/Mod-Translation-Styleguide/blob/master/glossary.md) they call it "粉", but in this mod it might cause confuse with "粉状矿石（Powdered Ore）".
  In Ex Nihilo dust is translated to "尘土", and I think it's not a good idea to translate it to "砂" or "沙".

**Comment by 3TUSK** [comment]
@h404bi I see. Thanks for your time spent on reply!

**Comment by chawyehsu** [comment]
@3TUSK 
np! you too!

I found that we can translate `dust` to "粉尘" while `powdered` is "粉状，粉末状的". Then we can call `Osmium Ore Dust` "锇矿石粉尘", which maybe better than "锇矿石尘土"? But "粉尘" seems to not be appropriate for a `block`, haha. (Don't talk about science in Minecraft.)

Besides, I think I need to remove "瓷" from follow lines:

```
item.bucket_porcelain_azoth.name=水银瓷桶
item.bucket_porcelain_raw.name=未烧制的瓷桶
item.bucket_porcelain_empty.name=瓷桶
item.bucket_porcelain_water.name=水瓷桶
item.bucket_porcelain_lava.name=熔岩瓷桶
item.bucket_porcelain_milk.name=牛奶瓷桶
item.bucket_porcelain_witchwater.name=女巫之水瓷桶
```

The original text don't contain word `porcelain`. ;p

**Pull request merged**
